shell.nix: fix openssl, export env vars, refactor
I encountered some errors trying to build this using direnv and Nix.

```console
$ cargo build
(...)
error: failed to run custom build command for `rust-lzma v0.2.1`
process didn't exit successfully: `/home/steveej/src/others/rdedup/target/debug/build/rust-lzma-5d3b1f2545b5a696/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Could not find liblzma using pkg-config', /home/steveej/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-lzma-0.2.1/build.rs:10:3
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

After exporting the variables I was still left with this error about openssl not found:

```console
$ cargo build
   Compiling openssl-sys v0.9.40
   Compiling idna v0.1.5
   Compiling atty v0.2.11
   Compiling which v1.0.5
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling rand v0.5.4
   Compiling time v0.1.40
error: failed to run custom build command for `openssl-sys v0.9.40`
process didn't exit successfully: `/home/steveej/src/others/rdedup/target/debug/build/openssl-sys-29710816a9b93766/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.40

', /home/steveej/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.40/build/main.rs:269:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
```

Using `openssl.dev` instead of `openssl` fixed this for me.